"use client"
// RootLayout.jsx
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar/NavBar";
import { Footer } from "./components/footer/Footer";
import { Providers } from "./Providers";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Green wave",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/images/Green-Wave.png" />
      </head>

      <body className={inter.className}>
        <Providers>
          {pathname === "/" ? (
            <>
              {children}
            </>
          ) : pathname.startsWith("/dashboard") ? (
            <>
              {children}
            </>
          ) : (
            <>
              <NavBar />
              {children}
              <Footer />
            </>
          )}
        </Providers>
      </body>
    </html>
  );
}
